# Generated by Django 5.2.17 on 2026-08-18 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('trusted', 'Trusted Vendor'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('identity_verified', models.BooleanField(default=False)),
                ('business_verified', models.BooleanField(default=False)),
                ('payment_history_verified', models.BooleanField(default=False)),
                ('transaction_history_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_verification', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_verifications_performed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
